/* eslint-env node, browser */
/* eslint strict: 0 */
/* global Module */

/**
 * @file The main entry point for libot.js. The {{lib}} and {{emscripten}}
 *       comments in this file will be replaced with the sources in lib and the
 *       generated Emscripten code, respectively.
 * @author Greg Curtis <greg.r.curtis@gmail.com>
 */

/* {{vendors}} */

/** @namespace libot */
var libot = {};

(function() {

    /**
     * Module is a variable created by Emscripten and contains all of the
     * functions exported by Emscripten. It is used whenever we want to do
     * something with code generated by Emscripten.
     *
     * @var {object} Module
     */
    /* {{emscripten}} */

    (function() {
        "use strict";

        var cFuncs = {};
        cFuncs.otNewOp = Module.cwrap("ot_new_op", null, ["number", "string"]);
        cFuncs.otSkip = Module.cwrap("ot_skip", null, ["number", "number"]);
        cFuncs.otInsert = Module.cwrap("ot_insert", null, ["number", "string"]);
        cFuncs.otDelete = Module.cwrap("ot_delete", null, ["number", "number"]);
        cFuncs.otEncode = Module.cwrap("ot_encode", "string", ["number"]);
        cFuncs.otDecode = Module.cwrap("ot_decode", "number", ["number", "string"]);
        cFuncs.otSnapshot = Module.cwrap("ot_snapshot", "string", ["number"]);

        /* {{lib}} */

        function isRunningInNode() {
            return (typeof module !== "undefined" && module.exports);
        }

        if (isRunningInNode()) {
            var ws = require("ws");
            module.exports = libot;
            var server = new libot.Server(ws);
            process.on("exit", function() {
                server.close();
            });
        }
    }());
}());
